# Generated by Django 5.2.8 on 2025-12-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ORGANIZER', 'Organisateur'), ('COMMITTEE', 'Membre du comité'), ('AUTHOR', 'Communicant / Auteur'), ('PARTICIPANT', 'Participant'), ('INVITED', 'Invité / Conférencier'), ('WORKSHOP_ANIMATOR', 'Animateur de workshop')], default='PARTICIPANT', max_length=30),
        ),
    ]
