# Generated by Django 5.2.8 on 2025-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='domain',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Administrateur ', 'Owner'), ('Organisateur d’événement', 'Organizer'), ('Communicant / Auteur', 'Author'), ('Membre du Comité  scientifique', 'Reviewer'), ('Participant', 'Participant'), ('Invité / Conférencier', 'Guest'), ('Animateur de Workshop ', 'Animator')], default='Participant', max_length=30),
        ),
    ]
