# Generated by Django 5.2.8 on 2025-12-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_event_options_event_invited_speakers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('abstract', models.TextField(verbose_name='Résumé')),
                ('keywords', models.CharField(max_length=500, verbose_name='keywords')),
                ('sub_type', models.CharField(choices=[('oral', 'oral'), ('poster', 'poster'), ('affiche', 'affiche')], default='oral', max_length=20, verbose_name='submission Type')),
                ('pdf_file', models.FileField(upload_to='submissions/%Y/%m/%d/', verbose_name='PDF_file')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('revision', 'revision')], default='pending', max_length=20, verbose_name='Statut')),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur principal')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.event', verbose_name='event')),
            ],
        ),
    ]
