# Generated by Django 6.0 on 2025-12-21 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('abstract', models.TextField(verbose_name='Résumé')),
                ('keywords', models.CharField(max_length=100, verbose_name='Keywords')),
                ('sub_type', models.CharField(choices=[('oral', 'oral'), ('poster', 'poster'), ('affiche', 'affiche')], default='oral', max_length=20, verbose_name='Submission Type')),
                ('pdf_file', models.FileField(upload_to='submissions/%Y/%m/%d/', verbose_name='PDF File')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('revision', 'revision')], default='pending', max_length=20, verbose_name='Statut')),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur Principal')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.event', verbose_name='Event')),
            ],
        ),
    ]
